import { basename, join } from "path";
import { homedir } from "os";
import type { ColorScheme } from "../../types";
import {
  ensureDir,
  writeConfigFile,
  readConfigFile,
  updateOrAppendLine,
  type ConfigUpdate,
} from "../utils";

export function configureWezTerm(scheme: ColorScheme, configDir?: string): void {
  const dirName = "wezterm";
  const baseDir = configDir ?? join(homedir(), ".config");
  const resolvedConfigDir = basename(baseDir) === dirName ? baseDir : join(baseDir, dirName);
  const colorsDir = join(resolvedConfigDir, "colors");
  const schemePath = join(colorsDir, "chromatic.toml");
  const mainConfigPath = join(resolvedConfigDir, "wezterm.lua");

  ensureDir(colorsDir);

  const toml = `# Chromatic colorscheme - generated by chromatic CLI
[colors]
foreground = "${scheme.foreground}"
background = "${scheme.background}"
cursor_bg = "${scheme.foreground}"
cursor_fg = "${scheme.background}"
cursor_border = "${scheme.activeBorder}"
selection_fg = "${scheme.background}"
selection_bg = "${scheme.activeBorder}"

ansi = [
  "${scheme.black}",
  "${scheme.red}",
  "${scheme.green}",
  "${scheme.yellow}",
  "${scheme.blue}",
  "${scheme.magenta}",
  "${scheme.cyan}",
  "${scheme.white}",
]

brights = [
  "${scheme.brightBlack}",
  "${scheme.brightRed}",
  "${scheme.brightGreen}",
  "${scheme.brightYellow}",
  "${scheme.brightBlue}",
  "${scheme.brightMagenta}",
  "${scheme.brightCyan}",
  "${scheme.brightWhite}",
]
`;

  writeConfigFile(schemePath, toml);

  ensureDir(resolvedConfigDir);
  let lua = readConfigFile(mainConfigPath);
  const updates: ConfigUpdate[] = [
    {
      pattern: /^\s*config\.color_scheme\s*=\s*['"][^'"]*['"]/m,
      line: `config.color_scheme = 'Chromatic'`,
    },
    {
      pattern: /^\s*color_scheme\s*=\s*['"][^'"]*['"]/m,
      line: `color_scheme = 'Chromatic'`,
    },
  ];
  let applied = false;
  for (const { pattern, line } of updates) {
    if (lua && pattern.test(lua)) {
      lua = updateOrAppendLine(lua, pattern, line);
      applied = true;
      break;
    }
  }
  if (!applied) {
    if (!lua || !lua.trim()) {
      lua = `local wezterm = require 'wezterm'\nlocal config = {}\nconfig.color_scheme = 'Chromatic'\nreturn config\n`;
      writeConfigFile(mainConfigPath, lua);
    }
  } else {
    writeConfigFile(mainConfigPath, lua);
  }
}
